apiVersion: batch/v1
kind: Job
metadata:
  name: renovate-job
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: renovate-config
        - name: log-share
          emptyDir: {}
      containers:
        - name: renovate
          # Update this to the latest available and then enable Renovate on
          # the manifest
          image: renovate/renovate:35.50-slim
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi
          # Environment Variables
          env:
            - name: LOG_LEVEL
              value: debug
          envFrom:
            - secretRef:
                name: renovate-env
          volumeMounts:
            - name: config-volume
              mountPath: /opt/renovate/
            - name: log-share
              mountPath: /app/renovate_logs

        - name: parser
          image: parser:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: log-share
              mountPath: /app/logs
          command: ['sh', '-c', 'sleep 90 && python3 src/logs_parser.py']
