apiVersion: batch/v1
kind: Job
metadata:
  name: renovate-job
spec:
  template:
    spec:
      containers:
        - name: renovate
          # Update this to the latest available and then enable Renovate on
          # the manifest
          image: renovate/renovate:35.50-slim
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi
          # Environment Variables
          env:
            - name: LOG_LEVEL
              value: debug
          envFrom:
            - secretRef:
                name: renovate-env
          volumeMounts:
            - name: config-volume
              mountPath: /opt/renovate/
            - name: work-volume
              mountPath: /app/renovate_logs
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: renovate-config
        - name: work-volume
          hostPath:
            path: /app/renovate_logs