apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  # GITHUB_COM_TOKEN: 'any-personal-user-token-for-github-com-for-fetching-changelogs'
  # You can set RENOVATE_AUTODISCOVER to true to run Renovate on all repos you have push access to
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_ENDPOINT: 'https://api.github.com/'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
  RENOVATE_TOKEN: ''
  RENOVATE_BASE_DIR: '/tmp/renovate/'
  RENOVATE_REPOSITORIES: '["ConradBohm/renovate_test_repo", "ConradBohm/renovate_second_test_repo"]'
  RENOVATE_DRY_RUN: 'lookup'
  RENOVATE_ONBOARDING: 'false'
  RENOVATE_PERSIST_REPO_DATA: 'false'
  RENOVATE_LOG_FILE: '/tmp/renovate/logs'